version: '3'

services:
  ftp:
    image: LPETERS006/docker-alpine-ftp-server
    container_name: ftp
    restart: unless-stopped
    environment:
      - USERS= swyx|swyx
    ports:
      - "21:21" 
      - "21000-21010:21000-21010"
    volumes:
      - "${FTP_FILES}:/ftp"
    cap_add:
      - 'ALL'
